var title,title_img;
var play,play_img;
var bg_img,bg;
var bg2,bg2_img;
var girl,girl_img;
var mousepointer,mousepointer_img;
var BgMusic;
var soundon,soundon_img,soundoff,soundoff_img;
var shirt1,shirt1_img,shirt1_girl,shirt1_girl_img;
var shirt2,shirt2_img,shirt2_girl,shirt2_girl_img;
var shirt3,shirt3_img,shirt3_girl,shirt3_girl_img;
var shirt4,shirt4_img,shirt4_girl,shirt4_girl_img;
var pant1,pant1_img,pant1_girl,pant1_girl_img;
var pant2,pant2_img,pant2_girl,pant2_girl_img;
var pant3,pant3_img,pant3_girl,pant3_girl_img;
var pant4,pant4_img,pant4_girl,pant4_girl_img;
var face1,face1_img,face1_girl,face1_girl_img;
var face2,face2_img,face2_girl,face2_girl_img;
var face3,face3_img,face3_girl,face2_girl_img;
var face4,face4_img,face4_girl,face4_girl_img;
var face5,face5_img,face5_girl,face5_girl_img;
var face6,face6_img,face6_girl,face6_girl_img;
var hair1,hair1_img,hair1_girl,hair1_girl_img;
var hair2,hair2_img,hair2_girl,hair2_girl_img;
var hair3,hair3_img,hair3_girl,hair3_girl_img;
var hair4,hair4_img,hair4_girl,hair4_girl_img;
var hair5,hair5_img,hair5_girl,hair5_girl_img;
var hair6,hair6_img,hair6_girl,hair6_girl_img;
var hair7,hair7_img,hair7_girl,hair7_girl_img;
var shirt1_face1,shirt1_face1_img;

function preload(){
  title_img = loadImage("images/title.png");
  play_img = loadImage("images/playbutton.png");
  bg_img = loadImage("images/bg.jpg");
  bg2_img = loadImage("images/bg2.jpg");
  girl_img = loadImage("images/defultgirl.png");
  mousepointer_img = loadImage("images/Mousepointer.png");
  shirt1_img = loadImage("images/Shirt1.png");
  shirt1_girl_img = loadImage("images/Shirt1_Worn.png");
  shirt2_img = loadImage("images/Shirt2.png");
  shirt2_girl_img = loadImage("images/Shirt2_Worn.png");
  shirt3_img = loadImage("images/Shirt3.png");
  shirt3_girl_img = loadImage("images/Shirt3_Worn.png");
  shirt4_img = loadImage("images/Shirt4.png");
  shirt4_girl_img = loadImage("images/Shirt4_Worn.png");
  BgMusic = loadSound("sounds/Wolf Moon - Unicorn Heads.mp3");
  soundon_img = loadImage("images/Soundon.png");
  soundoff_img = loadImage("images/SoundOFF.png");
  pant1_img = loadImage("images/Pant1.png");
  pant1_girl_img = loadImage("images/Pant1_Worn.png");
  pant2_img = loadImage("images/Pant2.png");
  pant2_girl_img = loadImage("images/Pant2_Worn.png");
  pant3_img = loadImage("images/Pant3.png");
  pant3_girl_img = loadImage("images/Pant3_Worn.png");
  pant4_img = loadImage("images/Pant4.png");
  pant4_girl_img = loadImage("images/Pant4_Worn.png");
  face1_img = loadImage("images/Face1.png");
  face1_girl_img = loadImage("images/Face1_Worn.png");
  face2_img = loadImage("images/Face2.png");
  face2_girl_img = loadImage("images/Face2_Worn.png");
  face3_img = loadImage("images/Face3.png");
  face3_girl_img = loadImage("images/Face3_Worn.png");
  face4_img = loadImage("images/Face4.png");
  face4_girl_img = loadImage("images/Face4_Worn.png");
  face5_img = loadImage("images/Face5.png");
  face5_girl_img = loadImage("images/Face5_Worn.png");
  face6_img = loadImage("images/Face6.png");
  face6_girl_img = loadImage("images/Face6_Worn.png");
  hair1_img = loadImage("images/Hair1.png");
  hair1_girl_img = loadImage("images/Hair1_Worn.png");
  hair2_img = loadImage("images/Hair2.png");
  hair2_girl_img = loadImage("images/Hair2_Worn.png");
  hair3_img = loadImage("images/Hair3.png");
  hair3_girl_img = loadImage("images/Hair3_Worn.png");
  hair4_img = loadImage("images/Hair4.png");
  hair4_girl_img = loadImage("images/Hair4_Worn.png");
  hair5_img = loadImage("images/Hair5.png");
  hair5_girl_img = loadImage("images/Hair5_Worn.png");
  hair6_img = loadImage("images/Hair6.png");
  hair6_girl_img = loadImage("images/Hair6_Worn.png");
  hair7_img = loadImage("images/Hair7.png");
  hair7_girl_img = loadImage("images/Hair7_Worn.png");
  shirt1_face1_img = loadImage("images/Shirt1_Face1.png");
}
function setup(){
    createCanvas(1280,644);

    BgMusic.loop();

    bg = createSprite(640,322);
    bg.scale=0.7;
    bg.addImage(bg_img);

    title = createSprite(650,80);
    title.scale = 1.5;
    title.addImage(title_img);

    play = createSprite(900,200);
    play.scale=0.2;
    play.addImage(play_img);

    bg2 = createSprite(640,322);
    bg2.addImage(bg2_img);
    bg2.scale =1.5;
    bg2.visible = false;

    soundon = createSprite(40,620);
    soundon.addImage(soundon_img);
    soundon.scale = 0.1;

    soundoff = createSprite(40,620);
    soundoff.addImage(soundoff_img);
    soundoff.scale = 0.05;
    soundoff.visible = false;

    girl = createSprite(640,332);
    girl.addImage(girl_img);
    girl.visible = false;

    shirt1 = createSprite(100,100);
    shirt1.addImage(shirt1_img);
    shirt1.scale=0.4;
    shirt1.visible = false;

    shirt1_girl = createSprite(640,322);
    shirt1_girl.addImage(shirt1_girl_img);
    shirt1_girl.visible = false;

    shirt2 = createSprite(100,250);
    shirt2.addImage(shirt2_img);
    shirt2.scale=0.4;
    shirt2.visible = false;

    shirt2_girl = createSprite(640,322);
    shirt2_girl.addImage(shirt2_girl_img);
    shirt2_girl.visible = false;

    shirt3 = createSprite(100,400);
    shirt3.addImage(shirt3_img);
    shirt3.scale=0.4;
    shirt3.visible = false;

    shirt3_girl = createSprite(640,322);
    shirt3_girl.addImage(shirt3_girl_img);
    shirt3_girl.visible = false;

    shirt4 = createSprite(100,550);
    shirt4.addImage(shirt4_img);
    shirt4.scale=0.4;
    shirt4.visible = false;

    shirt4_girl = createSprite(640,322);
    shirt4_girl.addImage(shirt4_girl_img);
    shirt4_girl.visible = false;

    pant1 = createSprite(1150,100);
    pant1.addImage(pant1_img);
    pant1.scale = 0.4;
    pant1.visible = false;

    pant1_girl = createSprite(640,322);
    pant1_girl.addImage(pant1_girl_img);
    pant1_girl.visible = false;

    pant2 = createSprite(1150,250);
    pant2.addImage(pant2_img);
    pant2.scale = 0.4;
    pant2.visible = false;

    pant2_girl = createSprite(640,322);
    pant2_girl.addImage(pant2_girl_img);
    pant2_girl.visible = false;

    pant3 = createSprite(1150,400);
    pant3.addImage(pant3_img);
    pant3.scale = 0.4;
    pant3.visible = false;

    pant3_girl = createSprite(640,322);
    pant3_girl.addImage(pant3_girl_img);
    pant3_girl.visible = false;

    pant4 = createSprite(1150,550);
    pant4.addImage(pant4_img);
    pant4.scale = 0.4;
    pant4.visible = false;

    pant4_girl = createSprite(640,322);
    pant4_girl.addImage(pant4_girl_img);
    pant4_girl.visible = false;

    face1 = createSprite(360,80);
    face1.addImage(face1_img);
    face1.scale = 0.2;
    face1.visible = false;

    face1_girl = createSprite(640,322);
    face1_girl.addImage(face1_girl_img);
    face1_girl.visible = false;

    face2 = createSprite(460,80);
    face2.addImage(face2_img);
    face2.scale = 0.2;
    face2.visible = false;

    face2_girl = createSprite(640,322);
    face2_girl.addImage(face2_girl_img);
    face2_girl.visible = false;

    face3 = createSprite(560,80);
    face3.addImage(face3_img);
    face3.scale = 0.2;
    face3.visible = false;

    face3_girl = createSprite(640,322);
    face3_girl.addImage(face3_girl_img);
    face3_girl.visible = false;

    face4 = createSprite(660,80);
    face4.addImage(face4_img);
    face4.scale = 0.2;
    face4.visible = false;

    face4_girl = createSprite(640,322);
    face4_girl.addImage(face4_girl_img);
    face4_girl.visible = false;

    face5 = createSprite(760,80);
    face5.addImage(face5_img);
    face5.scale = 0.2;
    face5.visible = false;

    face5_girl = createSprite(640,322);
    face5_girl.addImage(face5_girl_img);
    face5_girl.visible = false;

    face6 = createSprite(860,80);
    face6.addImage(face6_img);
    face6.scale = 0.2;
    face6.visible = false;

    face6_girl = createSprite(640,322);
    face6_girl.addImage(face6_girl_img);
    face6_girl.visible = false;

    hair1 = createSprite(300,550);
    hair1.addImage(hair1_img);
    hair1.scale = 0.3;
    hair1.visible = false;

    hair1_girl = createSprite(640,322);
    hair1_girl.addImage(hair1_girl_img);
    hair1_girl.scale = 0.8;
    hair1_girl .visible = false;

    hair2 = createSprite(410,550);
    hair2.addImage(hair2_img);
    hair2.scale = 0.3;
    hair2.visible = false;

    hair2_girl = createSprite(640,322);
    hair2_girl.addImage(hair2_girl_img);
    hair2_girl.scale = 0.8;
    hair2_girl .visible = false;

    hair3 = createSprite(520,550);
    hair3.addImage(hair3_img);
    hair3.scale = 0.3;
    hair3.visible = false;

    hair3_girl = createSprite(640,322);
    hair3_girl.addImage(hair3_girl_img);
    hair3_girl.scale = 0.9;
    hair3_girl .visible = false;

    hair4 = createSprite(620,550);
    hair4.addImage(hair4_img);
    hair4.scale = 0.3;
    hair4.visible = false;

    hair4_girl = createSprite(640,322);
    hair4_girl.addImage(hair4_girl_img);
    hair4_girl.scale = 0.8;
    hair4_girl .visible = false;

    hair5 = createSprite(720,550);
    hair5.addImage(hair5_img);
    hair5.scale = 0.3;
    hair5.visible = false;
    hair5.setCollider("rectangle",0,-15,170,300);

    hair5_girl = createSprite(640,322);
    hair5_girl.addImage(hair5_girl_img);
    hair5_girl .scale = 0.8;
    hair5_girl .visible = false;

    hair6 = createSprite(820,560);
    hair6.addImage(hair6_img);
    hair6.scale = 0.5;
    hair6.visible = false;
    hair6.setCollider("rectangle",0,-15,130,200);

    hair6_girl = createSprite(640,322);
    hair6_girl.addImage(hair6_girl_img);
    hair6_girl.scale = 0.8;
    hair6_girl .visible = false;

    hair7 = createSprite(920,550);
    hair7.addImage(hair7_img);
    hair7.scale = 0.3;
    hair7.visible = false;
    hair7.setCollider("rectangle",0,0,230,400);

    hair7_girl = createSprite(640,322);
    hair7_girl.addImage(hair7_girl_img);
    hair7_girl.scale = 0.8;
    hair7_girl .visible = false;

    shirt1_face1 = createSprite(640,322);
    shirt1_face1.addImage(shirt1_face1_img);
    shirt1_face1.visible = false;

    mousepointer = createSprite(0,0);
    mousepointer.addImage(mousepointer_img);
    mousepointer.scale = 0.1;
    
}

function draw(){
    background(0);

    mousepointer.x = World.mouseX;
    mousepointer.y = World.mouseY;

    if(mousePressedOver(soundon)){
      BgMusic.stop();
      soundoff.visible = true;
      soundon.visible = false;
    }
    
    if(mousePressedOver(play)){
       title.visible = false;
       play.visible = false;
       bg.visible = false;
       bg2.visible = true;
       girl.visible = true;
       shirt1.visible = true;
       shirt2.visible = true;
       shirt3.visible = true;
       shirt4.visible = true;
       pant1.visible = true;
       pant2.visible = true;
       pant3.visible = true;
       pant4.visible = true;
       face1.visible = true;
       face2.visible = true;
       face3.visible = true;
       face4.visible = true;
       face5.visible = true;
       face6.visible = true;
       hair1.visible = true;
       hair2.visible = true;
       hair3.visible = true;
       hair4.visible = true;
       hair5.visible = true;
       hair6.visible = true;
       hair7.visible = true;
       shirt1_face1.visible = false;
    }

    if(mousePressedOver(shirt1)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = true;
      if(shirt1_girl.visible = true){
        if(mousePressedOver(face1)){
          shirt1_face1.visible = true;
        }
     }
      shirt2.visible = true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(shirt2)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = true;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;

    }
    if(mousePressedOver(shirt3)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = true;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }
    if(mousePressedOver(shirt4)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = true;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(pant1)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = true;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(pant2)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = true;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(pant3)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = true;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(pant4)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = true;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(face1)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      if(shirt1_girl.visible = true){
        if(mousePressedOver(face1)){
          shirt1_face1.visible = true;
          shirt1_girl.visible = false;
          face1_girl.visible = false;
        }
     }
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = true;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(face2)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = true;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(face3)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = true;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(face4)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = true;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(face5)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = true;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(face6)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = true;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair1)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = true;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair2)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = true;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair3)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = true;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair4)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = true;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair5)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = true;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair6)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = true;
      hair7.visible = true;
      hair7_girl.visible = false;
    }

    if(mousePressedOver(hair7)){
      title.visible = false;
      play.visible = false;
      bg.visible = false;
      bg2.visible = true;
      girl.visible = false;
      shirt1.visible = true;
      shirt1_girl.visible = false;
      shirt2.visible= true;
      shirt2_girl.visible = false;
      shirt3.visible = true;
      shirt3_girl.visible = false;
      shirt4.visible = true;
      shirt4_girl.visible = false;
      pant1.visible = true;
      pant1_girl.visible = false;
      pant2.visible = true;
      pant2_girl.visible = false;
      pant3.visible = true;
      pant3_girl.visible = false;
      pant4.visible = true;
      pant4_girl.visible = false;
      face1.visible = true;
      face1_girl.visible = false;
      face2.visible = true;
      face2_girl.visible = false;
      face3.visible = true;
      face3_girl .visible = false;
      face4.visible = true;
      face4_girl.visible = false;
      face5.visible = true;
      face5_girl.visible = false;
      face6.visible = true;
      face6_girl.visible = false;
      hair1.visible = true;
      hair1_girl.visible = false;
      hair2.visible = true;
      hair2_girl.visible = false;
      hair3.visible = true;
      hair3_girl.visible = false;
      hair4.visible = true;
      hair4_girl.visible = false;
      hair5.visible = true;
      hair5_girl .visible = false;
      hair6.visible = true;
      hair6_girl.visible = false;
      hair7.visible = true;
      hair7_girl.visible = true;
    }
    
    drawSprites();
}